elasticsearch:
  hosts:
    - http://elasticsearch:9200
  index_name: audit_log
  username: elastic
  password: elastic

api:
  middlewares:
    cors:
      allow_origins:
        - rschu.me
        - intranet.int.nl-ix.net
      allow_credentials: true
      allow_methods:
        - POST
      allow_headers:
        - content-type
        - user-agent
