version: '3'
services:
  audit-logger:
    container_name: audit-logger
    build:
      context: .
      dockerfile: docker/audit-logger/Dockerfile
    env_file:
      - .env
    environment:
      - CONFIG_FILE_PATH=/app/config.yaml
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_URL=${ELASTIC_URL}
      - ELASTIC_INDEX_NAME=${ELASTIC_INDEX_NAME}
      - ELASTIC_HOSTS=${ELASTIC_HOSTS}
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "8000:8000"
    networks:
      audit_logger:
        ipv4_address: 172.70.0.2

  elasticsearch:
    container_name: elasticsearch
    image: arm64v8/elasticsearch:7.17.10
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - PIPELINE_WORKERS=4
      - LOG_LEVEL=debug
      - MONITORING_ENABLED=enabled
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: root
    restart: unless-stopped
    volumes:
      - sa_elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      audit_logger:
        ipv4_address: 172.70.0.3

  kibana:
    container_name: kibana
    build:
      context: ./docker/kibana
      dockerfile: Dockerfile
      args:
        KIBANA_VERSION: "7.17.10"
    env_file:
      - .env
    environment:
      - elasticsearch.hosts=elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_USERNAME}
    restart: unless-stopped
    volumes:
      - sa_kibana_data:/usr/share/kibana/data
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      audit_logger:
        ipv4_address: 172.70.0.4
    depends_on:
      - elasticsearch

  backup:
    container_name: backup
    image: busybox
    volumes:
      - sa_elasticsearch_data:/usr/share/elasticsearch/data
      - sa_kibana_data:/usr/share/kibana/data
      - ./backup:/backup
    command: sh ./backup/volume_backups.sh
    restart: "no"
    profiles:
      - backup

volumes:
  sa_elasticsearch_data:
  sa_kibana_data:

networks:
  audit_logger:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.70.0.0/16
          gateway: 172.70.0.1
